### ISSUE TITLE
Cross-Platform Meta-Issue

### ISSUE THREAD

**Issue by DavidBurkett** [GrinPlusPlus/GrinPlusPlus#43]
The following are the known changes required to build in linux:

* [x] Replace winsock with a cross-platform socket library
* [x] Replace declspec imports/exports with cross-platform ImportExport.h macros
* [x] Update all includes to use correct case for file/directory names
* [x] Add OS check around VirtualLock & VirtualUnlock in Secure.h
* [x] Update Ctrl-C & system clear calls in server to something OS-independent, or just always run in headless mode
* [ ] Update build instructions

**Comment by DavidBurkett** [comment]
Fully supports windows 7/8/10, Linux, and recent versions of Mac OS X.
